services:
  ldap:
    build:
      context: ./docker/ldap
    container_name: backstage_ldap
    environment:
      LDAP_ORGANISATION: 'Backstage'
      LDAP_DOMAIN: 'backstage.local'
      LDAP_ADMIN_PASSWORD: 'admin'
    ports:
      - '1389:389'
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

volumes:
  ldap_data:
  ldap_config:
